// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Movement struct {
	ID          string       `json:"id"`
	VehicleID   string       `json:"vehicleId"`
	Type        MovementType `json:"type"`
	Description *string      `json:"description,omitempty"`
	OccurredAt  time.Time    `json:"occurredAt"`
	Metadata    *string      `json:"metadata,omitempty"`
	CreatedBy   string       `json:"createdBy"`
	CreatedAt   time.Time    `json:"createdAt"`
}

type MovementInput struct {
	VehicleID   string       `json:"vehicleId"`
	Type        MovementType `json:"type"`
	Description *string      `json:"description,omitempty"`
	OccurredAt  time.Time    `json:"occurredAt"`
	Metadata    *string      `json:"metadata,omitempty"`
}

type MovementReportRow struct {
	Type  MovementType `json:"type"`
	Count int32        `json:"count"`
}

type Mutation struct {
}

type Query struct {
}

type Role struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Role      *Role     `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type Vehicle struct {
	ID           string        `json:"id"`
	Vin          string        `json:"vin"`
	Name         string        `json:"name"`
	ModelCode    string        `json:"modelCode"`
	TractionType TractionType  `json:"tractionType"`
	ReleaseYear  int32         `json:"releaseYear"`
	BatchNumber  string        `json:"batchNumber"`
	Color        *string       `json:"color,omitempty"`
	Mileage      int32         `json:"mileage"`
	Status       VehicleStatus `json:"status"`
	CreatedAt    time.Time     `json:"createdAt"`
	UpdatedAt    time.Time     `json:"updatedAt"`
	Movements    []*Movement   `json:"movements"`
}

type VehicleInput struct {
	Vin          string         `json:"vin"`
	Name         string         `json:"name"`
	ModelCode    string         `json:"modelCode"`
	TractionType TractionType   `json:"tractionType"`
	ReleaseYear  int32          `json:"releaseYear"`
	BatchNumber  string         `json:"batchNumber"`
	Color        *string        `json:"color,omitempty"`
	Mileage      *int32         `json:"mileage,omitempty"`
	Status       *VehicleStatus `json:"status,omitempty"`
}

type VehicleUpdateInput struct {
	Name         *string        `json:"name,omitempty"`
	ModelCode    *string        `json:"modelCode,omitempty"`
	TractionType *TractionType  `json:"tractionType,omitempty"`
	ReleaseYear  *int32         `json:"releaseYear,omitempty"`
	BatchNumber  *string        `json:"batchNumber,omitempty"`
	Color        *string        `json:"color,omitempty"`
	Mileage      *int32         `json:"mileage,omitempty"`
	Status       *VehicleStatus `json:"status,omitempty"`
}

type MovementType string

const (
	MovementTypeSale         MovementType = "SALE"
	MovementTypeDefect       MovementType = "DEFECT"
	MovementTypeDiscontinued MovementType = "DISCONTINUED"
	MovementTypeTransfer     MovementType = "TRANSFER"
	MovementTypeReturn       MovementType = "RETURN"
)

var AllMovementType = []MovementType{
	MovementTypeSale,
	MovementTypeDefect,
	MovementTypeDiscontinued,
	MovementTypeTransfer,
	MovementTypeReturn,
}

func (e MovementType) IsValid() bool {
	switch e {
	case MovementTypeSale, MovementTypeDefect, MovementTypeDiscontinued, MovementTypeTransfer, MovementTypeReturn:
		return true
	}
	return false
}

func (e MovementType) String() string {
	return string(e)
}

func (e *MovementType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MovementType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MovementType", str)
	}
	return nil
}

func (e MovementType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MovementType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MovementType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TractionType string

const (
	TractionTypeRwd    TractionType = "RWD"
	TractionTypeFwd    TractionType = "FWD"
	TractionTypeAwd    TractionType = "AWD"
	TractionTypeFourWd TractionType = "FOUR_WD"
)

var AllTractionType = []TractionType{
	TractionTypeRwd,
	TractionTypeFwd,
	TractionTypeAwd,
	TractionTypeFourWd,
}

func (e TractionType) IsValid() bool {
	switch e {
	case TractionTypeRwd, TractionTypeFwd, TractionTypeAwd, TractionTypeFourWd:
		return true
	}
	return false
}

func (e TractionType) String() string {
	return string(e)
}

func (e *TractionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TractionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TractionType", str)
	}
	return nil
}

func (e TractionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TractionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TractionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VehicleStatus string

const (
	VehicleStatusActive       VehicleStatus = "ACTIVE"
	VehicleStatusInactive     VehicleStatus = "INACTIVE"
	VehicleStatusDiscontinued VehicleStatus = "DISCONTINUED"
)

var AllVehicleStatus = []VehicleStatus{
	VehicleStatusActive,
	VehicleStatusInactive,
	VehicleStatusDiscontinued,
}

func (e VehicleStatus) IsValid() bool {
	switch e {
	case VehicleStatusActive, VehicleStatusInactive, VehicleStatusDiscontinued:
		return true
	}
	return false
}

func (e VehicleStatus) String() string {
	return string(e)
}

func (e *VehicleStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VehicleStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VehicleStatus", str)
	}
	return nil
}

func (e VehicleStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VehicleStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VehicleStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
