package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/Kenfoxfire/Gear-Core-app/internal/graph/model"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Signup - signup"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	// TODO testy
	u, tok, err := r.Auth.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	// mOve to func separate
	return &model.AuthPayload{Token: tok, User: &model.User{
		ID: strconv.FormatInt(u.ID, 10), Email: u.Email,
		Role:      &model.Role{ID: strconv.FormatInt(u.Role.ID, 10), Name: u.Role.Name, CreatedAt: u.Role.CreatedAt},
		CreatedAt: u.CreatedAt,
	}}, nil
}

// CreateVehicle is the resolver for the createVehicle field.
func (r *mutationResolver) CreateVehicle(ctx context.Context, input model.VehicleInput) (*model.Vehicle, error) {
	panic(fmt.Errorf("not implemented: CreateVehicle - createVehicle"))
}

// UpdateVehicle is the resolver for the updateVehicle field.
func (r *mutationResolver) UpdateVehicle(ctx context.Context, id string, input model.VehicleUpdateInput) (*model.Vehicle, error) {
	panic(fmt.Errorf("not implemented: UpdateVehicle - updateVehicle"))
}

// DeleteVehicle is the resolver for the deleteVehicle field.
func (r *mutationResolver) DeleteVehicle(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteVehicle - deleteVehicle"))
}

// CreateMovement is the resolver for the createMovement field.
func (r *mutationResolver) CreateMovement(ctx context.Context, input model.MovementInput) (*model.Movement, error) {
	panic(fmt.Errorf("not implemented: CreateMovement - createMovement"))
}

// ChangeUserRole is the resolver for the changeUserRole field.
func (r *mutationResolver) ChangeUserRole(ctx context.Context, userID string, newRole string) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangeUserRole - changeUserRole"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Vehicle is the resolver for the vehicle field.
func (r *queryResolver) Vehicle(ctx context.Context, id string) (*model.Vehicle, error) {
	panic(fmt.Errorf("not implemented: Vehicle - vehicle"))
}

// Vehicles is the resolver for the vehicles field.
func (r *queryResolver) Vehicles(ctx context.Context, limit *int32, offset *int32) ([]*model.Vehicle, error) {
	panic(fmt.Errorf("not implemented: Vehicles - vehicles"))
}

// MovementReport is the resolver for the movementReport field.
func (r *queryResolver) MovementReport(ctx context.Context, from time.Time, to time.Time) ([]*model.MovementReportRow, error) {
	panic(fmt.Errorf("not implemented: MovementReport - movementReport"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
